### ISSUE TITLE
White sheet when creating a connection

### ISSUE THREAD

**Issue by Broiler95** [datalens-tech/datalens#33]
After installation I can't create connections. When I click "Create connection" I only see a white sheet.

In the cmopose file all parameters are standard.

**Comment by Nealbow** [comment]
Same issue for me.
Here's the log from ui container
```
{"level":30,"time":1697538981941,"pid":11,"hostname":"f34a675d2c4d","name":"datalens-full","id":"dl.88524.0b94065e","method":"POST","url":"/gateway/root/bi/getConnectors","headers":{"host":"192.168.1.149","x-forwarded-for":"192.168.128.1","connection":"close","content-length":"0","accept":"application/json, text/plain, */*","x-timezone-offset":"-180","accept-language":"ru","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46","x-request-id":"dl.88524.0b94065e","content-type":"application/x-www-form-urlencoded","origin":"http://192.168.1.149:18080","referer":"http://192.168.1.149:18080/workbooks/w8yu4yy11ikql/connections/new","accept-encoding":"gzip, deflate","cookie":"[REDACTED]"},"remoteAddress":"::ffff:127.0.0.1","remotePort":55612,"msg":"[Express POST] Request started [dl.88524.0b94065e]"}
{"level":30,"time":1697538981945,"pid":11,"hostname":"f34a675d2c4d","name":"datalens-full","msg":"[Express POST] [gateway] [Gateway bi getConnectors [rest]] Initiating request [dl.88524.0b94065e]"}
{"level":30,"time":1697538981945,"pid":11,"hostname":"f34a675d2c4d","name":"datalens-full","debugHeaders":{"x-api-request-method":"GET","x-api-request-url":"http://control-api:8080/api/v1/info/connectors","x-api-request-lang":"ru","x-request-id":"dl.88524.0b94065e","x-gateway-version":"1.0.5"},"msg":"[Express POST] [gateway] [Gateway bi getConnectors [rest]] Starting request [dl.88524.0b94065e]"}
{"level":50,"time":1697538981952,"pid":11,"hostname":"f34a675d2c4d","name":"datalens-full","err":{"type":"Object","message":"Request failed with status code 500","stack":"AxiosError: Request failed with status code 500\n    at settle (/opt/app/node_modules/axios/dist/node/axios.cjs:1909:12)\n    at IncomingMessage.handleStreamEnd (/opt/app/node_modules/axios/dist/node/axios.cjs:2989:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","debug":{"requestUrl":"http://control-api:8080/api/v1/info/connectors","responseStatus":500}},"extra":{"actionURL":"http://control-api:8080/api/v1/info/connectors","parsedError":{"status":500,"message":"Gateway request error","code":"GATEWAY_REQUEST_ERROR","details":{"title":"500 Internal Server Error","description":""}},"serviceName":"bi","debugHeaders":{"x-api-request-method":"GET","x-api-request-url":"http://control-api:8080/api/v1/info/connectors","x-api-request-lang":"ru","x-request-id":"dl.88524.0b94065e","x-gateway-version":"1.0.5"}},"msg":"[Express POST] [gateway] [Gateway bi getConnectors [rest]] Request failed [dl.88524.0b94065e]"}
192.168.128.1 - - [17/Oct/2023:10:36:21 +0000] "POST /gateway/root/bi/getConnectors HTTP/1.1" 500 176 "http://192.168.1.149:18080/workbooks/w8yu4yy11ikql/connections/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46"
{"level":50,"time":1697538981953,"pid":11,"hostname":"f34a675d2c4d","name":"datalens-full","extra":{"responseTime":12,"statusCode":"500","headers":{"x-request-id":"dl.88524.0b94065e","surrogate-control":"no-store","cache-control":"no-store, max-age=0, must-revalidate, proxy-revalidate","content-type":"application/json; charset=utf-8","content-length":"176"}},"msg":"[Express POST] Request failed [dl.88524.0b94065e]"}

``` 
I noticed calls to container control-api, and checked the logs from there. It looks like it has a problems with initialization, here's the log from `control-api`
```
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dl_control_api/app.py", line 87, in <module>
    app = create_uwsgi_app()
  File "/usr/local/lib/python3.10/dist-packages/dl_control_api/app.py", line 56, in create_uwsgi_app
    settings = load_settings_from_env_with_fallback(ControlApiAppSettings)
  File "/usr/local/lib/python3.10/dist-packages/dl_configs/settings_loaders/loader_env.py", line 661, in load_settings_from_env_with_fallback
    return EnvSettingsLoader(effective_env).load_settings(
  File "/usr/local/lib/python3.10/dist-packages/dl_configs/settings_loaders/loader_env.py", line 620, in load_settings
    fallback_cfg = fallback_cfg_resolver.resolve(effective_s_dict)
  File "/usr/local/lib/python3.10/dist-packages/dl_configs/settings_loaders/fallback_cfg_resolver.py", line 102, in resolve
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/backend-configs/api.yaml'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
{"level": "DEBUG", "message": "[17/Oct/2023:10:36:21 +0000] 192.168.128.8 GET /api/v1/info/connectors 500 [0 msecs|104 B]"}
```

**Comment by Nealbow** [comment]
Looks like I found a solution.
There is no file `api.yaml` in container `datalens-data-api`
It exists in `datalens-control-api` but not in `datalens-data-api`

**Comment by Nealbow** [comment]
Ooh, I should have taken a closer look at the contents of `docker-compose.yml`
It states that both containers include the `CONFIG_PATH` variable, which by default in the configuration leads to volume.
To launch the service correctly, you must either create the `backend_configs` directory yourself near `docker-compose.yml`, in which you place the api.yaml file from the repository, or follow the launch instructions from the `README`.
It doesn’t look entirely obvious, but if you follow the instructions, the necessary directory hierarchy is created for correct launch.

**Comment by belonesox** [comment]
Same problem (even with «git clone») I have running DL with podman-docker. 
Solution — «chmod a+rX . -R» for all clone directory.
